#!/usr/bin/env bash
# a Bash script that pings an IP address passed as an argument

ping_host() {
    if [ "$#" -eq 0 ]; then
        echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
        exit 1
    else
        ping -c 5 "$1"
    fi
}

ping_host "$@"
