#!/usr/bin/env bash
# A Bash script that displays "To infinity and beyond" indefinitely.
# Requirement: Add a sleep 2 in between each iteration of the loop.
counter=1
while true; do
    while [ $counter -le 5 ]; do
        echo "To infinity and beyond"
        sleep 2
        ((counter++))
    done
    counter=1
done
