#!/usr/bin/env bash
#a Bash script that prints numbers ranging from 1 to 100.

#!/bin/bash

for ((i = 1; i <= 100; i++)); do
    case $((i % 15)) in
        0) echo "FizzBuzz" ;;
        3 | 6 | 9 | 12) echo "Fizz" ;;
        5 | 10) echo "Buzz" ;;
        *) echo "$i" ;;
    esac
done
