#!/usr/bin/env bash
# using while loop to display "Best School" 10 times, but for the 9th iteration, displays
# "Best School" and then Hi on a new line.

i=1
while ((i<=11))
do
   if ((i == 10))
   then
      echo "Hi"
   else
      echo "Best School"
   fi
   ((i++))
done
