#!/usr/bin/env bash
# a Bash script that loops from 1 to 10 and:
# display "Best School" by default
# display "bad luck" the 4th time
# display "good luck" the 8th time

i=1
while [ $i -le 10 ]
do 
    if [ $i -eq 4 ]
    then
        echo "bad luck";
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School";         
    fi

    (("i++"));
done
