#!/usr/bin/env bash
# A Bash script to configure Ubuntu:
# localhost to 127.0.0.2, facebook.com to 8.8.8.8.

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
